### ISSUE TITLE
Problem with PDF Viewer in WEB

### ISSUE THREAD

**Issue by OneimadO** [owncloud/files_pdfviewer#106]
Hi everybody,

I have some problems with the PDF Viewer in my owncloud installation, at the beginning we have no problem with it but since two days when i try to open a pdf i have this:

http://image.noelshack.com/fichiers/2016/10/1457604996-owncloud-server-8-2-owncloud-forums-mozilla-firefox.jpg

When i download this PDF in Adobe it's fine and i have no bug.

Thanks in advance.

**Comment by LukasReschke** [comment]
@OneimadO Please upload the PDF as well. We can't debug this otherwise.

**Comment by OneimadO** [comment]
All my PDF are impacted, 2 days ago my PDF works.

**Comment by OneimadO** [comment]
[MONTP ETUDE ENVIRONNEMENTALE.pdf](https://github.com/owncloud/files_pdfviewer/files/167274/MONTP.ETUDE.ENVIRONNEMENTALE.pdf)

An example

**Comment by blacktuxedoz** [comment]
Hi everyone,

first of all sorry for my bad english,recently i found a problem when showing any pdf files on firefox.
since there is a lot of issues about PDF not showing, unexpected server response, etc.

this step is not very smart for all masters here, but it work for me though.

i'm using firefox 45.0.2.
here's the step:

1. go to help on firefox choose troubleshoot information.
2. try safe mode - this will disable all of your add-ons on firefox.
3. try again to access or view your PDF file using owncloud as usually.
4. if it work then there is one or more your add-ons is causing the problems.
5. restart firefox on normal mode (refresh firefox)

in my problem is unexpected server response and the add-on that was on problem showing pdf file is IDMan. disable it then restart firefox.

thats it. its so simple. hope my experience can help solve your problem from showing PDF file from owncloud.

**Comment by PVince81** [comment]
please try again with 0.9.0 as we've updated the [pdf.js](https://github.com/mozilla/pdf.js) library
