### ISSUE TITLE
Owncloud pdf viewer not showing data in forms.

### ISSUE THREAD

**Issue by tradge** [owncloud/files_pdfviewer#114]
Here is a screenshot of the preview
http://imgur.com/lNepi0Y

Here is the actual file with data filled in.
[MLF_1040616_Letterhead&Envelope.pdf](https://github.com/owncloud/files_pdfviewer/files/235109/MLF_1040616_Letterhead.Envelope.pdf)

**Comment by DeepDiver1975** [comment]
It I open the pdf locally with the desktop app I also don't see the data.
Only once the test is selected.

**Comment by nextroom** [comment]
Hi Thomas, thanks for your work.
I have the same problem, if you download the pdf of the second link you will see that it is filled.
The same thing happens to me with the completed pdf.
sometimes I simply change the characters, for example instead of showing a "5" it shows an "R" or instead of showing a "0" it shows the "M".

thank you for your help

**Comment by PVince81** [comment]
We've updated pdf.js, please try again with the 0.9.0 version of the app.

This is likely an upstream issue.

I also wonder whether the data is really saved inside the PDF file or just cached somewhere on the local computer.

**Comment by PVince81** [comment]
upstream: https://github.com/mozilla/pdf.js
