### ISSUE TITLE
PDF files can't be opened in trashbin

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/files_pdfviewer#50]
### Steps to reproduce

1. Upload pdf files.
2. Delete it.
3. Open it in the trashbin.

### Expected behaviour
File is opened.

### Actual behaviour
View gets broken.

![screen shot 2015-05-07 at 11 04 27](https://cloud.githubusercontent.com/assets/9048796/7511907/f2eb241a-f4a8-11e4-9d35-95f2f964712b.png)

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
Postgresql

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.4","versionstring":"8.1 alpha 3","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in community edition.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Chrome 41

**Comment by SergioBertolinSG** [comment]
Perhaps the expected behaviour should be not opening pdf viewer at all.

**Comment by PVince81** [comment]
Yes, currently the trashbin should not display any previews.

The problem is that there is no reliable generic way for apps to say "give me the URL to the selected file with the correct content". Some apps even have their own endpoints for loading files (like text editor) which makes it extra-tricky.

For now viewer apps should not trigger themselves in the trashbin.

**Comment by PVince81** [comment]
Cannot reproduce on 9.1.1
