### ISSUE TITLE
pdfViewer seems to have problems showing some images.

### ISSUE THREAD

**Issue by farson2003** [owncloud/files_pdfviewer#63]
I cannot be much more specific, but certain documents (it appears when containing images), do not show correctly. Pdfviewer does not show some of their images.

(This is especially troublesome, when opening a scanned document with the pdfviewer and then all that shows is a blank white page),
(I cannot attach the specific document here due to data protection reasons, but maybe somebody else can help out).

When opening locally with AdobePDF, the document shows properly.

**Comment by Mitchou** [comment]
Same here !

**Comment by cheesewizz** [comment]
Me too, its only display a white page or blank with firefox 40.0 but work with chrome, I havent try in IE,
https://forum.owncloud.org/viewtopic.php?f=31&t=30237&sid=8f00867d8a981ee8303a92efaf64a6bb
 is there any workaround?

thanks

**Comment by jcallerykbi** [comment]
I believe this issue and https://github.com/owncloud/files_pdfviewer/issues/60 are the same.  You can work around it in Firefox by changing security.csp.enable to false in about:config.  However I believe you are taking a security hit in Firefox as this setting is universal.

**Comment by jcallerykbi** [comment]
Here is the error in Chrome:

>Refused to load the image 'blob:https%3A//mycloud_dev.kbibiopharma.com/28be200e-cf62-454e-8cac-5511bdb759b4' because it violates the following Content Security Policy directive: "img-src 'self'".

Which is strange, because what I can tell from this is that the only "safe" image source pdfviewer sees is 'self', when both 'self' and data: are hard coded in the Allowed Images array in contentsecuritypolicy.php.

However, if I add data: to the img-src array using $policy.addAllowedImageDomain('data:') in displaycontroller.php, data: will then show in the error, but it still will not work:  

>Refused to load the image 'blob:https%3A//mycloud_dev.kbibiopharma.com/d6f363cd-011e-47f7-aec1-44d2f3f5e205' because it violates the following Content Security Policy directive: "img-src 'self' data:".

Maybe this will help.

**Comment by jcallerykbi** [comment]
Sorry!  looks like I was looking at two different versions of Owncloud.  Data: is NOT hardcoded in the Allowed Images domain for the version I am using as my dev server, which is 8.1.1.  However,  shouldn't adding data: to the allowed domains still work?

Thanks

**Comment by LukasReschke** [comment]
Please test Please test https://github.com/owncloud/files_pdfviewer/pull/65

**Comment by volkswagner** [comment]
I too get blank pages or partial content when viewing certain .pdf files using Owncloud server 8.1.

An easy way to reproduce the problem:
    1) Create a Google Doc, add text and a photo
    2) Use Google file menu and "download as pdf"
    3) Upload to owncloud
    4) View .pdf with viewer and see there will be no picture, but it does exist in the file.

I have similar issue with scanned documents from my Brother MFC5890CN printer/scanner.
Theses scans show as blank documents on Owncloud web viewer. This is true with most 
tested browsers.

**Comment by jataylor99** [comment]
I'm also getting the same error using Chrome Version 45.0.2454.101 m with OwnCloud server 8.1.  Certain PDFs that used to display a preview before downloading are now coming up blank.  The preview shows the right size and shape of the PDF file, but it's blank.  Upon further inspection in Chrome, it says "Refused to load the image 'blob:https%3A//XXX.XXX.XXX.XXX%3A8443/1cc3d710-b323-4ea5-a389-c0ff32f8be77' because it violates the following Content Security Policy directive: "img-src 'self'".   It works fine in MS Explorer.

Does anyone know how to adjust the Content Security Policy settings in Chrome?  That seems to be the issue here.

**Comment by jataylor99** [comment]
After digging a little more into Lukas' post, I was able to solve it.  You just need to edit the ../owncloud/apps/files_pdfviewer/controller/displaycontroller.php file and add:

$policy->addAllowedImageDomain('*');

as shown in this post:  https://github.com/owncloud/files_pdfviewer/commit/b46d2cfb9f22fd17d0c92988bff08249ef1b153a

Thanks, Lukas!
